// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwPrx9WYeJBhPTkgLrmEwJdfzO_ukg43U',
    appId: '1:895763334632:web:21820ad7baaff3f94f905d',
    messagingSenderId: '895763334632',
    projectId: 'femease',
    authDomain: 'femease.firebaseapp.com',
    storageBucket: 'femease.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80q1u8ZPGOLar7QSwWXdYKtGK6VCulv0',
    appId: '1:895763334632:android:a6f50eaa0191813e4f905d',
    messagingSenderId: '895763334632',
    projectId: 'femease',
    storageBucket: 'femease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLG-0wJU8VRXDMmW26sa883Q691clBJYI',
    appId: '1:895763334632:ios:62c497b2c9e076784f905d',
    messagingSenderId: '895763334632',
    projectId: 'femease',
    storageBucket: 'femease.appspot.com',
    iosClientId: '895763334632-f2vufe3nc3o9er2k05aqelubhkeg0tc5.apps.googleusercontent.com',
    iosBundleId: 'me.chandramdutta.femease',
  );
}
